#!/usr/bin/ruby

require_relative 'task'
require_relative 'todo_list'

@todo_list = TodoList.new
@todo_list.read_todo(ARGV[0])

def dispatch #Global
  case ARGV[1]
  when "add"
    t = Task.new
    t.description = ARGV[2]
    @todo_list.add_task(t)
  when "remove"

  when "change_status"

  when "assign"

  when "reassign"

  when "instruction"
    instruction
  end
end

dispatch
@todo_list.print
