#!/usr/bin/ruby

require_relative 'task'
require_relative 'todo_list'
require_relative 'command'
require 'rainbow/ext/string'

@todo_list = TodoList.new(ARGV[0]="./todo_folder/0.txt")
@todo_list.read_todo
@todo_list.instruction
@todo_list.print if @todo_list.tasks

commands = []

while line = $stdin.gets

  if line.rstrip == "undo"
    commands.last.undo
    commands.pop
  else
    commands.push(Command.new(@todo_list, line))
    commands.last.execute
  end

  puts "*******"
  @todo_list.print
  p commands.map { |c| c.name }
  puts "*******"
  @todo_list.write_todo
end
